/**
 * AI glossary-term translator.
 *
 * Fills in the MISSING per-language translations of a glossary's own terms by
 * asking a translate-capable module to translate each term's source into the
 * project's active languages. Unlike the regular translation hot path (M9),
 * this works directly on glossary terms — no masking, LQA, TM, routing or run
 * tracking — because the inputs are short, bounded term sources.
 *
 * Module selection mirrors {@link selectSuggestModule} in glossary-generator:
 * an explicit `moduleId` wins, otherwise the cheapest enabled/active module.
 * Per-run `model`/`reasoningEffort` overrides flow through the same
 * resolveEffectiveModuleConfig → createWithConfig path. Constant terms are kept
 * verbatim (never translated), and already-filled cells are left untouched.
 */
import type {
  GlobalConfig,
  GlossaryTerm,
  Project,
  TranslationJob,
  TranslationModule,
} from '@zercade-dev/narn-shared';
import { PSEUDO_MODULE_ID, resolveBatchGrouping } from '@zercade-dev/narn-shared';
import { moduleRegistry } from './M6-module-registry.js';
import { getGlobalConfigStore, getGlossaryStore, getProjectStore } from '../storage/registry.js';
import { selectCapableModule } from './M9/module-selection.js';
import { ReadOnlyGlossaryError } from '../types/errors.js';

export class GlossaryTranslateNotPossibleError extends Error {
  readonly statusCode = 409;

  constructor(message: string) {
    super(message);
    this.name = 'GlossaryTranslateNotPossibleError';
  }
}

export interface TranslateGlossaryTermsRequest {
  /** Explicit module selection; otherwise the cheapest translate-capable module. */
  moduleId?: string;
  /** Per-run model override. */
  model?: string;
  /** Per-run reasoning-effort override (module config key `reasoningEffort`). */
  reasoningEffort?: string;
}

export interface TranslateGlossaryTermsResult {
  /** Number of (term × language) translation cells filled in. */
  translated: number;
  /** Number of distinct terms that received at least one new translation. */
  terms: number;
}

/** Resolve a translate-capable module (mirrors glossary-generator's selectSuggestModule). */
function selectTranslateModule(
  project: Project,
  global: GlobalConfig,
  sessionId: string | undefined,
  request: TranslateGlossaryTermsRequest,
): TranslationModule {
  const requestedId = request.moduleId;
  return selectCapableModule(moduleRegistry, project, global, sessionId, {
    ...(requestedId !== undefined ? { requestedId } : {}),
    ...(request.model ? { requestedModel: request.model } : {}),
    ...(request.reasoningEffort ? { requestedEffort: request.reasoningEffort } : {}),
    // Exclude the pseudo module: it is bound to the synthetic pseudo-test
    // language and must never fill in real glossary translations.
    capability: (m) => m.id !== PSEUDO_MODULE_ID && typeof m.translate === 'function',
    notPossible: (msg) => new GlossaryTranslateNotPossibleError(msg),
    requestedFailLabel: `module "${requestedId}" cannot translate`,
    noneAvailableMessage: 'no enabled translate-capable module available',
  }).module;
}

/**
 * Translates a glossary's terms into the project's active languages, filling
 * only the missing translation cells. Skips constant terms (kept verbatim) and
 * cells that already have a non-empty value. Returns how many cells/terms were
 * filled. Throws {@link ReadOnlyGlossaryError} for read-only glossaries and
 * {@link GlossaryTranslateNotPossibleError} (409) when no module can translate.
 */
export async function translateGlossaryTerms(
  projectId: string,
  glossaryId: string,
  request: TranslateGlossaryTermsRequest = {},
  sessionId?: string,
  signal?: AbortSignal,
): Promise<TranslateGlossaryTermsResult> {
  const [project, global, glossary] = await Promise.all([
    getProjectStore().loadProject(projectId),
    getGlobalConfigStore().load(),
    getGlossaryStore().getGlossary(projectId, glossaryId),
  ]);

  if (glossary.readOnly) {
    throw new ReadOnlyGlossaryError(glossaryId);
  }

  const targetLanguages = project.activeLanguages.filter((l) => l !== project.sourceLanguage);

  // One job per (non-constant term × target language) where the translation is
  // missing/empty. The term id rides through as `entryId` so results map back.
  // A term's `notes` (its meaning/usage/gender hint, e.g. generated by "Generate
  // glossaries") rides through as `context` so LLM modules use it as translation
  // guidance; non-LLM modules ignore it.
  const jobs: TranslationJob[] = [];
  for (const term of glossary.terms) {
    if (term.constant) continue;
    const source = term.source.trim();
    if (!source) continue;
    const context = term.notes?.trim();
    for (const targetLanguage of targetLanguages) {
      if (term.translations[targetLanguage]?.trim()) continue;
      jobs.push({
        entryId: term.id,
        sourceText: term.source,
        targetLanguage,
        sourceLanguage: project.sourceLanguage,
        ...(context ? { context } : {}),
      });
    }
  }

  if (jobs.length === 0) {
    // Verify a module is available even when there's nothing to do, so the UI
    // reports "no module" rather than a misleading "all done".
    selectTranslateModule(project, global, sessionId, request);
    return { translated: 0, terms: 0 };
  }

  const module = selectTranslateModule(project, global, sessionId, request);
  // Glossary terms carry no categories/glossary footprint, so dimension grouping
  // is undefined here; only the "ignore batch size limit" toggle is meaningful —
  // when on, send all term jobs in one provider call instead of chunking.
  const { ignoreSizeLimit } = resolveBatchGrouping(project, global.settings);
  const results = await module.translate(
    jobs,
    signal,
    ignoreSizeLimit ? { ignoreSizeLimit: true } : undefined,
  );

  // Group the successful translations back onto their term, then persist each
  // touched term once (merging so sibling-language translations survive).
  const filledByTerm = new Map<string, Record<string, string>>();
  for (const result of results) {
    if (result.error || !result.translatedText.trim()) continue;
    const filled = filledByTerm.get(result.entryId) ?? {};
    filled[result.targetLanguage] = result.translatedText;
    filledByTerm.set(result.entryId, filled);
  }

  const termsById = new Map<string, GlossaryTerm>(glossary.terms.map((t) => [t.id, t]));
  let translated = 0;
  for (const [termId, filled] of filledByTerm) {
    const term = termsById.get(termId);
    if (!term) continue;
    translated += Object.keys(filled).length;
    await getGlossaryStore().updateTerm(projectId, glossaryId, termId, {
      translations: { ...term.translations, ...filled },
    });
  }

  return { translated, terms: filledByTerm.size };
}
