#!/usr/bin/env bash
# Remove all autogenerated files in the workspace.
#
# This is destructive: it wipes installed dependencies, build output,
# the local pnpm store, generated runtime data, and lockfile-adjacent
# caches. Use it when you want a from-scratch state before reinstalling.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "==> Resetting workspace at $ROOT"

# 1. Root-level caches
echo "    Removing root node_modules and .pnpm-store"
rm -rf node_modules .pnpm-store

# 2. Per-package generated content
echo "    Removing per-package node_modules, dist, coverage, tsbuildinfo"
find packages -type d \( \
    -name 'node_modules' -o \
    -name 'dist' -o \
    -name 'coverage' \
  \) -prune -exec rm -rf {} +
find packages -type f -name '*.tsbuildinfo' -delete

# 3. Server runtime data (project files created by the API)
if [[ -d packages/server/projects ]]; then
  echo "    Removing packages/server/projects"
  rm -rf packages/server/projects
fi

# 4. Optional: prune the global pnpm store (only if pnpm is available)
if command -v pnpm >/dev/null 2>&1; then
  echo "    Pruning global pnpm store"
  pnpm store prune || true
fi

echo "==> Reset complete. Run 'pnpm install' to reinstall dependencies."
